config/routes.rb
Socialtrip::Application.routes.draw do
  get "welcome/index"

  post "welcome/authorize"

  match '/users/auth/facebook' => 'users/omniauth_callbacks#facebook'
  
  match '/welcome/authorize' => 'welcome#authorize'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :users, :controllers => { :invitations => 'invitations' } do
    post  "/users/invitation/batch_invite" => "invitations#batch_invite", :as => "batch_invitation"
    get "users/invitations/new" => "invitations#new", :as => "new_invitation"
  end

  resources :trips do
    member do
      post 'create_invitation'
    end
  end

   root :to => 'welcome#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :user_id, :name, :destination, :start_date, :end_date, :description

  has_many :invitations
  has_many :fb_invitees
  has_many :users, :through => :invitations

  validates_presence_of :name, :destination, :description, :start_date, :end_date

  before_validation :parse_date_values

  before_destroy :delete_associated_invitations

  def invite!(invitee)
    if user = Provider.user_exists?(invitee[:uid])
      invite = invitations.build(:user_id => user.id)
      invite.save
    else
      invitee = fb_invitees.build(:invitee_uid => invitee[:uid], :name => invitee[:name])
      invitee.save
    end
  end

  def invitee_already_present?(fb_id)
    fb_invitees.where(:invitee_uid => fb_id).first ? nil : "No" 
  end

  def collect_uids
    fb_invitees.collect(&:invitee_uid)
  end

  def mail_invitees
    users.select{|u| u.providers.where(:user_provider => 'facebook').empty?}.uniq_by(&:email)
  end

  def facebook_invitees_name
    (users.select{|u| u.providers.where(:user_provider => 'facebook').present?}.collect(&:full_name) + FbInvitee.where(:trip_id => id).collect(&:name)).uniq
  end
  
  def members
    users.select{|u| u.full_name.present?}.collect(&:full_name).flatten.join(',')
  end

  private

    def parse_date_values
      parse_start_date if start_date.present?
      parse_end_date if end_date.present?
    end

    def parse_start_date
      self.start_date = start_date.to_date.to_s(:mysql_format)
    end

    def parse_end_date
      self.end_date = end_date.to_date.to_s(:mysql_format)
    end

    def delete_associated_invitations
      invitations.destroy_all
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :initialize_trip, :only => [:new, :create]
  before_filter :load_trip, :only => [:edit, :destroy, :show, :update, :create_invitation]

  def index
    @trips = current_user.trips
  end

  def new; end

  def show; end

  def create
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @trip.update_attributes(params[:trip])
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    if @trip.destroy
      redirect_to trips_path
    end
  end

  def create_invitation
    if @trip.invite!(params[:invitee])
      render :json => {:status => 200}
    else
      render :json => {:status => 304}
    end
  end

  private

    def initialize_trip
      @trip = Trip.new(params[:trip])
      @trip.invitations.build(:user_id => current_user.id)
    end

    def load_trip
      @trip = current_user.trips.where(:id => params[:id]).first
    end
    
end

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>

  <% if @trip.errors.any? %>
    <ul style="color:red;">
      <% @trip.errors.full_messages.each do |err_msg| %>
        <li><%= err_msg  %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :destination %>
  <%= f.text_field :destination %><br />

  <%= f.label :start_date %>
  <%= f.text_field :start_date, :class => "datepicker", :readonly => true %><br />

  <%= f.label :end_date %>
  <%= f.text_field :end_date, :class => "datepicker", :readonly => true %><br />

  <%= f.label :description %>  
  <%= f.text_area :description, :class => "field span5", :id => "textarea", :rows => "8" %><br />

  <%= f.submit "#{@trip.new_record? ? "Create" : "Update"} Trtp", class: "btn btn-primary"  %>
<% end %>

app/views/trips/edit.html.erb
<legend>Edit Trip</legend>
<%= render 'form' %>

app/views/trips/index.html.erb
<legend>All my trips</legend>
<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Name</th>
    <th>Destination</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Description</th>
    <th colspan='3'>Actions</th>
  </tr>

  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.name %></td>
      <td><%= trip.destination %></td>
      <td><%= trip.start_date %></td>
      <td><%= trip.end_date %></td>
      <td><%= trip.description %></td>
      <td><%= link_to "Show", trip_path(trip)  %></td>
      <td><%= link_to "Edit", edit_trip_path(trip)  %></td>
      <td><%= link_to "Destroy", trip_path(trip), :method => :delete, :confirm => 'Are you sure?'  %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Create new trip", new_trip_path %>

app/views/trips/new.html.erb
<legend>New Trip</legend>
<%= render 'form' %>

app/views/trips/show.html.erb
<legend><%= @trip.name %></legend>
<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <td>Destination:</td>
    <td><%= @trip.destination %></td>
  </tr>
  <tr>
    <td>Start Date:</td>
    <td><%= @trip.start_date %></td>
  </tr>
  <tr>
    <td>End Date:</td>
    <td><%= @trip.end_date %></td>
  </tr>
  <tr>
    <td>Description:</td>
    <td><%= @trip.description %></td>
  </tr>
  <tr>
    <td>Members:</td>
    <td><%= @trip.members %></td>
  </tr>
</table>



<% if user_signed_in? %>
  <div id='friends'>
    <% if current_user.has_signed_up_using_fb?  %>
      <p><%= link_to  "Invite your facebook friends", 'javascript:void', :id => 'invite_fb_friends' %></p>

      <%= text_field_tag :invite_friends, nil, :id => 'fb-friends', :placeholder => "Type in friend's name" %>
    <% end %>

    <div id='email-invitation'>
      <%= link_to  "Invite friends to this trip", "javascript:void", :id => 'invite_by_email' %>
      <div class="email-invitation-form">
      </div>
    </div>
  </div>
<% end %>

<script src="/facebook_all.js" type="text/javascript"></script>

<div class="mail_invitees">
  <h3>Email Invitees</h3>
  <% @trip.mail_invitees.each do |user| %>
    <%= user.email %>
  <% end %>
</div>


<div class="facebook_invitees">
  <h3>FB Invitees</h3>
  <% @trip.facebook_invitees_name.each do |name| %>
    <%= name %>
  <% end %>
</div>

<% if current_user.has_signed_up_using_fb?  %>
  <script>
    $(function(){
      
      $('#invite_by_email').click(function(){
        $.ajax({
          url: "<%= new_invitation_path(:trip_id => @trip.id) %>",
          dataType: 'json',
          method: 'get',

          success: function(data, textStatus, jqXHR) {
    			  if (jqXHR.status == 200){
    			    $('.email-invitation-form').html(data.tmplt);
              $('#email_ids').tagsInput({
                'defaultText':'Enter comma seprated email ids',
                'width' : '500px',
                'height' : '170px'
              });

              $('#email_ids_tag').width('195px');    			    
    			  }
    			}
        });
      });
      
      
      invited_uids = "<%= @trip.collect_uids %>";

      FB.init({
        appId: '129652407201708',
        cookie: false,
        status: true,
        xfbml : true
      });

      $('#fb-friends').hide();

      $('a#invite_fb_friends').click(function(){
        $.ajax({
          url: "https://graph.facebook.com/<%= current_user.fb_id %>/friends?fields=name,picture&access_token=<%= current_user.fb_token %>",
          method: 'get',
          dataType: 'json',

          success: function(friends, textStatus, jqXHR){
            if(jqXHR.status == 200){
              $('#fb-friends').show();

              friends_json = format_json(friends['data']);
              
              $( "#fb-friends" ).autocomplete({
                source: friends_json,

                select: function( event, ui ) {
                  if(invited_uids.indexOf(ui.item.uid) >= 0){
                    alert("You have alredy invited "+ui.item.label+" to this trip.");
                  }else{
                    request.send_trip_request_on_fb(ui);
                  }
                }              
              }).data( "autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li></li>" )
                .data( "item.autocomplete", item ).val(item.uid)
                .append( "<a><img src=" + item.profile_pic_url +  "><strong>" + item.label + "</strong></a>" )
                .appendTo( ul );
              }
            }
          }
        });
      });

      $('#invite_by_email').click(function(){
        
      });
    });

    var request = {
      send_trip_request_on_fb : function(ui_hash) {
        var ui = ui_hash;
        FB.ui({method: 'apprequests',
          to: ui_hash.item.uid,
          title: 'Invitation to trip',
          message: '<%= current_user.first_name %> added you to his trip to <%= @trip.destination %> on Socialtrip.com',
        }, 
        function(response){
          if(response){
            request.send_trip_request_on_app(ui);
          }
        });
      },
      send_trip_request_on_app : function(ui_hash) {
        create_trip_request(ui_hash.item.uid, ui_hash.item.label);
      }
    }

    var format_json = function(fb_data){
      formatted_json = []

      $.each(fb_data, function(index, data){
        formatted_json.push({"label" : data.name, "uid" : data.id, "profile_pic_url" : data.picture.data.url});
      });

      return formatted_json;
    }

    var create_trip_request = function(fb_uid, full_name){
      $.ajax({
        url: "<%= create_invitation_trip_path(@trip) %>",
        method: 'post',
        dataType: 'json',
        data: {'invitee': {'uid': fb_uid, 'name': full_name}},

        beforeSend: function(xhr) {
          set_csrf_token(xhr);
        },        

        success: function(data, textStatus, jqXHR){
          if(jqXHR.status == 200){

          }
        }
      });
    }
  </script>
<% end %>