config/routes.rb
Socialtrip::Application.routes.draw do
  get "welcome/index"

  post "welcome/authorize"

  match '/users/auth/facebook' => 'users/omniauth_callbacks#facebook'
  
  match '/welcome/authorize' => 'welcome#authorize'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :users, :controllers => { :invitations => 'invitations' } do
    post  "/users/invitation/batch_invite" => "invitations#batch_invite", :as => "batch_invitation"
    get "users/invitations/new" => "invitations#new", :as => "new_invitation"
  end

  resources :trips do
    member do
      post 'create_invitation'
    end
  end

   root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	skip_before_filter :authenticate_user!, only: [:index]

  def index
  end
  
  def authorize
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/authorize.html.erb
<script type='text/javascript'>
  top.location.href = 'http://localhost:3000/auth/facebook';
</script>

app/views/welcome/index.html.erb
<div class="hero-unit margin100">
  <h1>Welcome to Tripize</h1>
  <p>Tourize.com</p>
  <p>
  	<% unless user_signed_in? %>
	  	<a class="btn btn-primary btn-large" heef="#">Learn more</a>
		<% else %>
			<%= link_to "Manage Trips", trips_path, class: "btn btn-primary btn-large" %>
		<% end %>		  	
  </p>
</div>

app/views/welcome/welcome.html.erb
<script type='text/javascript'>
  top.location.href = 'http://localhost:3000/auth/facebook';
</script>